CREATE TABLE ABOUTPROD
   (	"PRODID" VARCHAR2(6 BYTE) NOT NULL, 
	"SLNO" NUMBER(2,0) NOT NULL ENABLE, 
	"ABOUT" VARCHAR2(2000 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "ABOUTPROD_PK" PRIMARY KEY ("PRODID", "SLNO"),
	CONSTRAINT "ABOUTPROD_FK1" FOREIGN KEY ("PRODID")
	  REFERENCES "SCOTT"."PRODUCTS" ("PRODID") 
   )
/
CREATE TABLE CATEGORY
   (	"CATID" NUMBER(4,0), 
	"MAINCAT" VARCHAR2(20 BYTE) NOT NULL, 
	"SUBCAT" VARCHAR2(50 BYTE) NOT NULL, 
	"FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CRTDT" DATE DEFAULT sysdate, 
	"CAT_DESC" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("CATID")
   )
/
CREATE TABLE CUST_ADDR
   (	"CUSTID" VARCHAR2(5 BYTE), 
	"SLNO" NUMBER(1,0), 
	"ALIAS_NAME" VARCHAR2(20 BYTE), 
	"ADDR1" VARCHAR2(100 BYTE), 
	"ADDR2" VARCHAR2(100 BYTE), 
	"ADDR3" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"STATE" VARCHAR2(30 BYTE), 
	"PINCODE" NUMBER(6,0), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "PK_CUST_ADDR" PRIMARY KEY ("CUSTID", "SLNO"),
	 CONSTRAINT "FK_CUST_ID" FOREIGN KEY ("CUSTID")
	  REFERENCES "SCOTT"."USERMASTER" ("CUSTID")
   )
/
CREATE TABLE CUST_CART
   (	"CUSTID" VARCHAR2(5 BYTE), 
	"PRODID" VARCHAR2(6 BYTE), 
	"SLNO" NUMBER(1,0), 
	"QTY" NUMBER(5,0), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "CUST_CART_FK1" FOREIGN KEY ("PRODID")
	  REFERENCES "SCOTT"."PRODUCTS" ("PRODID") , 
	 CONSTRAINT "CUST_CART_FK2" FOREIGN KEY ("CUSTID")
	  REFERENCES "SCOTT"."USERMASTER" ("CUSTID") , 
	 CONSTRAINT "CUST_CART_FK3" FOREIGN KEY ("PRODID", "SLNO")
	  REFERENCES "SCOTT"."PROD_VARIANT" ("PRODID", "SLNO")
   )
/
CREATE TABLE CUST_WALLET 
   (	"CUSTID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"SLNO" NUMBER(1,0) NOT NULL ENABLE, 
	"WALLET_NAME" VARCHAR2(20 BYTE), 
	"AMOUNT" NUMBER(9,2), 
	"FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CRTDT" DATE DEFAULT sysdate, 
	"LASTUSEDT" DATE, 
	 CONSTRAINT "CUST_WALLET_PK" PRIMARY KEY ("CUSTID", "SLNO"),
  	CONSTRAINT "CUST_WALLET_FK1" FOREIGN KEY ("CUSTID")
	  REFERENCES "SCOTT"."USERMASTER" ("CUSTID") 
   )
/
CREATE TABLE ORDERDETAIL 
   (	"ORDERID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ITEMNO" NUMBER(2,0) NOT NULL ENABLE, 
	"PRODID" VARCHAR2(6 BYTE), 
	"SLNO" NUMBER(1,0), 
	"QTY" NUMBER(2,0), 
	"UNITPRICE" NUMBER(10,2), 
	"SHIPPING" NUMBER(5,0), 
	"DISCOUNT" NUMBER(10,2), 
	"FINALPRICE" NUMBER(10,2), 
	"SELLERID" VARCHAR2(5 BYTE), 
	"TRANID" VARCHAR2(6 BYTE), 
	 CONSTRAINT "ORDERDETAIL_PK" PRIMARY KEY ("ORDERID", "ITEMNO"),
  	CONSTRAINT "ORDERDETAIL_FK1" FOREIGN KEY ("PRODID", "SLNO")
	  REFERENCES "SCOTT"."PROD_VARIANT" ("PRODID", "SLNO") ,
	 CONSTRAINT "ORDERDETAIL_FK3" FOREIGN KEY ("ORDERID")
	  REFERENCES "SCOTT"."ORDERMASTER" ("ORDERID") 
   )
/
CREATE TABLE ORDERMASTER 
   (	"ORDERID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CUSTID" VARCHAR2(5 BYTE), 
	"PAYMENT" VARCHAR2(20 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	"ASLNO" NUMBER(1,0), 
	 CONSTRAINT "ORDERMASTER_PK" PRIMARY KEY ("ORDERID"),
  	 CONSTRAINT "ORDERMASTER_FK1" FOREIGN KEY ("CUSTID")
	  REFERENCES "SCOTT"."USERMASTER" ("CUSTID"), 
	 CONSTRAINT "ORDERMASTER_FK2" FOREIGN KEY ("CUSTID", "ASLNO")
	  REFERENCES "SCOTT"."CUST_ADDR" ("CUSTID", "SLNO")
   )
/
CREATE TABLE "SCOTT"."ORDERSTATUS" 
   (	"ORDERID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ITEMNO" NUMBER(2,0) NOT NULL ENABLE, 
	"STATUSID" NUMBER(2,0) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(50 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "ORDERSTATUS_PK" PRIMARY KEY ("ORDERID", "ITEMNO", "STATUSID"),
  	CONSTRAINT "ORDERSTATUS_FK2" FOREIGN KEY ("STATUSID")
	  REFERENCES "SCOTT"."STATUS" ("STATUSID"), 
	 CONSTRAINT "ORDERSTATUS_FK1" FOREIGN KEY ("ORDERID", "ITEMNO")
	  REFERENCES "SCOTT"."ORDERDETAIL" ("ORDERID", "ITEMNO") 
   )
/
CREATE TABLE PROD_IMAGE 
   (	"PRODID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"SLNO" NUMBER(2,0) NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(50 BYTE), 
	"PATH" VARCHAR2(50 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	"FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"FLAGDT" DATE, 
	"IMGDESC" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PROD_IMAGE_PK" PRIMARY KEY ("PRODID", "SLNO"), 
	 CONSTRAINT "PROD_IMAGE_FK1" FOREIGN KEY ("PRODID")
	  REFERENCES "SCOTT"."PRODUCTS" ("PRODID")
   ) 
/
CREATE TABLE PROD_SPEC 
   (	"PRODID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"SLNO" NUMBER(2,0) NOT NULL ENABLE, 
	"SPEC" VARCHAR2(30 BYTE), 
	"SPECVAL" VARCHAR2(50 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	"FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"FLAGDT" DATE, 
	"UNIT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PROD_SPEC_PK" PRIMARY KEY ("PRODID", "SLNO")
   )
/
CREATE TABLE "SCOTT"."PROD_VARIANT" 
   (	"PRODID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"SLNO" NUMBER(1,0) NOT NULL ENABLE, 
	"VARIANT" VARCHAR2(30 BYTE), 
	"QTY" NUMBER(5,0), 
	"UNITPRICE" NUMBER(8,2), 
	"DISCOUNT" NUMBER(2,0), 
	"DELIVERY" NUMBER(3,0), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "PROD_VARIANT_PK" PRIMARY KEY ("PRODID", "SLNO"), 
	 CONSTRAINT "PROD_VARIANT_FK1" FOREIGN KEY ("PRODID")
	  REFERENCES "SCOTT"."PRODUCTS" ("PRODID")
   )
/
CREATE TABLE PRODFEEDBACK 
   (	"PRODID" VARCHAR2(6 BYTE), 
	"FHEADER" VARCHAR2(100 BYTE), 
	"FEEDBACK" VARCHAR2(1000 BYTE), 
	"CRTBY" VARCHAR2(5 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "PRODFEEDBACK_FK1" FOREIGN KEY ("PRODID")
	  REFERENCES "SCOTT"."PRODUCTS" ("PRODID")
   )
/
CREATE TABLE "SCOTT"."PRODLIKE" 
   (	"PRODID" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"LTYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"CRTBY" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "PRODLIKE_PK" PRIMARY KEY ("PRODID", "LTYPE", "CRTBY"), 
	 CONSTRAINT "PRODLIKE_FK1" FOREIGN KEY ("PRODID")
	  REFERENCES "SCOTT"."PRODUCTS" ("PRODID") 
   )
/
CREATE TABLE PRODREVIEW 
   (	"PRODID" VARCHAR2(6 BYTE), 
	"RATING" NUMBER(1,0), 
	"HEADLINE" VARCHAR2(100 BYTE), 
	"REVIEW" VARCHAR2(1000 BYTE), 
	"REVIEWER" VARCHAR2(5 BYTE), 
	"CRTDT" DATE DEFAULT sysdate
   )
/
CREATE TABLE PRODUCTS
   (	"PRODID" VARCHAR2(6 BYTE), 
	"CATID" NUMBER(4,0), 
	"PROD_DESC" VARCHAR2(100 BYTE), 
	"CUSTID" VARCHAR2(5 BYTE), 
	"FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CRTDT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("PRODID"), 
	 CONSTRAINT "PRODUCTS_FK1" FOREIGN KEY ("CATID")
	  REFERENCES "SCOTT"."CATEGORY" ("CATID"), 
	 CONSTRAINT "PRODUCTS_FK2" FOREIGN KEY ("CUSTID")
	  REFERENCES "SCOTT"."USERMASTER" ("CUSTID") 
   )
/
CREATE TABLE STATUS 
   (	"STATUSID" NUMBER(2,0) NOT NULL ENABLE, 
	"STATUSDESC" VARCHAR2(30 BYTE), 
	 CONSTRAINT "STATUS_PK" PRIMARY KEY ("STATUSID")
   )
/
CREATE TABLE TEMPLATE
   (	"CATID" NUMBER(4,0) NOT NULL ENABLE, 
	"SLNO" NUMBER(2,0) NOT NULL ENABLE, 
	"SPEC" VARCHAR2(30 BYTE), 
	"UNIT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TEMPLATE_PK" PRIMARY KEY ("CATID", "SLNO"), 
	 CONSTRAINT "TEMPLATE_FK1" FOREIGN KEY ("CATID")
	  REFERENCES "SCOTT"."CATEGORY" ("CATID")
   )
/
CREATE TABLE TRANSACTIONMASTER 
   (	"TRANID" VARCHAR2(6 BYTE), 
	"CUSTID" VARCHAR2(5 BYTE), 
	"WSLNO" NUMBER(1,0), 
	"SELLERID" VARCHAR2(5 BYTE), 
	"AMOUNT" NUMBER(10,2), 
	"CRTDT" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("TRANID")
   )
/
CREATE TABLE "SCOTT"."USERMASTER" 
   (	"CUSTID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"MOBILE" NUMBER(10,0), 
	"DOB" DATE, 
	"PWD" VARCHAR2(30 BYTE), 
	"CRTDT" DATE DEFAULT sysdate, 
	"USERID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE) DEFAULT 'M', 
	"UPDTDT" DATE, 
	"CUSTTYPE" VARCHAR2(1 BYTE) DEFAULT 'C', 
	"ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"INACTIVEDT" DATE, 
	"ABOUT" VARCHAR2(100 BYTE), 
	 CONSTRAINT "CUSTOMER_MASTER_PK" PRIMARY KEY ("CUSTID"), 
	 CONSTRAINT "CUST_MASTER_UK1" UNIQUE ("USERID")
   )
/
CREATE TABLE "SCOTT"."WISHLIST" 
   (	"CUSTID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"SLNO" NUMBER(2,0) NOT NULL ENABLE, 
	"PRODID" VARCHAR2(6 BYTE), 
	"PSLNO" NUMBER(2,0), 
	"CRTDT" DATE DEFAULT sysdate, 
	 CONSTRAINT "WISHLIST_PK" PRIMARY KEY ("CUSTID", "SLNO"), 
	 CONSTRAINT "WISHLIST_FK1" FOREIGN KEY ("PRODID", "PSLNO")
	  REFERENCES "SCOTT"."PROD_VARIANT" ("PRODID", "SLNO") , 
	 CONSTRAINT "WISHLIST_FK2" FOREIGN KEY ("CUSTID")
	  REFERENCES "SCOTT"."USERMASTER" ("CUSTID")
   )
/
CREATE OR REPLACE FORCE VIEW "SCOTT"."VWORDER" ("ORDERID", "CUSTOMERID", "PAYMENT", "CRTDT", "PRODID", "ITEMNO", "QTY", "UNITPRICE", "UPRICE", "DISCOUNT", "FINALPRICE", "SELLPRICE", "SHIPPING", "SELLERNAME", "TRANID", "PROD_DESC", "VARIANT", "WALLET_NAME", "ALIAS_NAME", "ADDR1", "ADDR2", "ADDR3", "CITY", "STATE", "PINCODE", "PATH", "FILENAME", "STATUSID", "STATUS", "REMARK", "STATUSDT") AS 
select a.orderid,a.CUSTID customerid,a.payment,to_char(a.crtdt,'DD-Mon-YYYY') crtdt,b.prodid, b.itemno,b.qty,b.unitprice,to_char(b.unitprice,'9,99,99,999.99') uprice,b.discount,b.finalprice,to_char(b.finalprice,'9,99,99,999.99') sellprice,b.shipping,h.user_name sellername,b.tranid,c.prod_desc,d.variant,e.wallet_name,
g.ALIAS_NAME,g.ADDR1,g.ADDR2,g.ADDR3,g.CITY,g.STATE,g.PINCODE, i.path,i.filename,j.statusid ,j.statusdesc,k.remarks,to_char(k.crtdt,'DD-Mon-YYYY')
from
ordermaster a, orderdetail b, products c, prod_variant d, cust_wallet e, transactionmaster f,cust_addr g,usermaster h,prod_image i,status j, orderstatus k
where
a.orderid=b.orderid and
b.prodid=c.prodid and
b.prodid=d.prodid and
b.slno=d.slno and
a.custid=e.custid and
b.tranid=f.tranid and
f.wslno=e.slno and
a.custid=g.custid and
a.aslno=g.slno and
i.prodid=c.prodid and
i.prodid=b.prodid and
i.slno=(select min(slno) from prod_image where prodid=b.prodid) and
h.custid=b.sellerid and
j.statusid=k.statusid and
k.statusid=(select max(statusid) from orderstatus where orderid=b.orderid and itemno=b.itemno) and
k.orderid=b.orderid and
k.itemno=b.itemno
/
CREATE OR REPLACE FORCE VIEW "SCOTT"."VWSEARCH" ("PRODID", "STEXT") AS 
select a.prodid,a.prod_desc ||' '||b.variant||' '||e.maincat||' '||e.subcat from products a, prod_variant b, category e
where a.prodid=b.prodid and a.catid=e.catid
union
select prodid,about from aboutprod
union
select prodid, spec||' '|| specval||' '||unit  from prod_spec where specval is not null
/










